export const GET_POSTS_CATEGORY = 'app/PostCategory/GET_POSTS_CATEGORY';
export const GET_POSTS_CATEGORY_SUCCESS =
  'app/PostCategory/GET_POSTS_CATEGORY_SUCCESS';
export const GET_POSTS_CATEGORY_ERROR =
  'app/PostCategory/GET_POSTS_CATEGORY_ERROR';
