export const GET_ALL_CATEGORIES = 'app/home/GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_SUCCESS = 'app/home/GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_ERROR = 'app/home/GET_ALL_CATEGORIES_ERROR';
